### ISSUE TITLE
Removes images

### ISSUE THREAD

**Issue by juanr2001** [imagemin/imagemin#214] opened 2016-11-16 15:56 UTC
Do you know why imagemin removes my images when compressing them?

For example: From 2198 -> 0 bytes

https://www.evernote.com/l/AkRtJWvQVAxEjZDH1IwX7iyRVxYYyFWwO_kB/image.png

**Comment by shinnn** [comment] 2017-01-08 11:36
Probably duplicate of https://github.com/imagemin/imagemin/issues/185

**Closed by shinnn** 2017-01-08 11:36 UTC
