### ISSUE TITLE
Failed to build dependencies due to issue with kavva/bin-build

### ISSUE THREAD

**Issue by joneslee85** [imagemin/imagemin#128] opened 2015-10-17 09:22 UTC
This morning I got following errors when `npm install`:

```
> optipng-bin@3.0.2 postinstall /Users/tle/src/envato/unstock/node_modules/optipng-bin
> node lib/install.js

  ⚠ connect ETIMEDOUT
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/tle/src/envato/unstock/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/
node_modules/got/index.js:167:24)
    at EventEmitter.emit (events.js:107:17)
    at ClientRequest.<anonymous> (/Users/tle/src/envato/unstock/node_modules/optipng-bin/node_modules/bin-build/node_modules/download
/node_modules/got/index.js:50:7)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:317:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

This issue is caused by the fact that `imagemin` relies on latest version of `bin-build` which is [broken](https://github.com/kevva/bin-build/issues/6).

I think `imagemin` should lock `bin-build` to `2.1.1`.

For the time being, users could work around with overriding the `bin-build` version in their `packages.json`:

```
  "dependencies": {
    "imagemin": {
      "version": "^3.2.0",
      "from": "imagemin/imagemin",
      "dependencies": {
        "bin-build": {
          "version": "2.1.1",
          "from": "kevva/bin-build"
        }
      }
    },
```

**Comment by shinnn** [comment] 2015-10-17 09:34
> I think `imagemin` should lock `bin-build` to `2.1.1`.

You can create a great pull request to fix https://github.com/sindresorhus/got/issues/79.

**Comment by shinnn** [comment] 2015-10-17 09:35
And this issue is just a duplicate of https://github.com/imagemin/imagemin/issues/110.

**Closed by shinnn** 2015-10-17 09:35 UTC
