### ISSUE TITLE
Add PATH variable to download binary from custom URL

### ISSUE THREAD

**Issue by pd4d10** [imagemin/imagemin#239] opened 2017-03-29 10:56 UTC
Like `PHANTOMJS_CDNURL` for PhantomJS, see

https://github.com/Medium/phantomjs#deciding-where-to-get-phantomjs

Is it possible to accept a PR to add this feature?

Related: https://github.com/imagemin/pngquant-bin/issues/63

**Comment by fagerbua** [comment] 2017-11-15 10:56
Duplicate of #183?

**Closed as completed** 2018-07-23 03:27 UTC
