### ISSUE TITLE
pPipe(...) is not a function

### ISSUE THREAD

**Issue by Kraxxis** [imagemin/imagemin#244] opened 2017-05-12 16:17 UTC
Just started getting lots of build failures, exceptions coming from this project. 

Version: 5.3.0

Stack trace:

ERROR in ./src/components/i/loader.svg
Module build failed: TypeError: pPipe(...) is not a function
    at Function.module.exports.buffer (/home/user/local-dev/git/project/node_modules/imagemin/index.js:64:60)
    at Object.module.exports (/home/user/local-dev/git/project/node_modules/image-webpack-loader/index.js:73:8)
 @ ./src/components/navigation/notification.jsx 27:14-42
 @ ./src/components/navigation/status-overlay.jsx
 @ ./src/components/navigation/nav-container.jsx
 @ ./src/components/navigation/screen.jsx
 @ ./src/components/main-screen.jsx
 @ ./src/module.js
 @ ./src/lib.js

**Comment by obble80** [comment] 2017-05-12 16:19
Confirmed we have just started suffering the same failure.

**Comment by kaicataldo** [comment] 2017-05-12 16:21
Dupe of https://github.com/imagemin/imagemin/issues/243

**Comment by Kraxxis** [comment] 2017-05-12 16:43
It looks like the error was because the author of commit [2310105](https://github.com/imagemin/imagemin/commit/2310105f7080a54b04268b0a848657986b6f4d10) felt it was necessary to replace established packages "mkdirp" and "promise.pipe" with his own, less used, packages "make-dir" and "p-pipe".

I find that odd.

**Comment by kaicataldo** [comment] 2017-05-12 16:49
@Kraxxis That's not a particularly helpful tone. Open source is volunteer work, and we're lucky that the author is willing to spend their free time working on this project.

**Comment by mariagandica** [comment] 2017-05-12 17:07
Hello, I have the same issue, can someone help me on how to fix this?

Thanks!

**Comment by Kraxxis** [comment] 2017-05-12 17:08
@mariagandica I have found a temporary work around is to install and pin the previous version of `imagemin` in your project like so:

`npm install imagemin@5.2.2 --save-dev`

**Comment by mariagandica** [comment] 2017-05-12 17:15
Thank you @Kraxxis I'm new to this so I'm gonna try!

**Comment by sindresorhus** [comment] 2017-05-12 18:07
The tests were passing, but turns out they were faulty so they didn't catch this issue. Should be fixed in the latest patch release. If you want to prevent this from happening again, help us increase the test coverage.

**Closed** 2017-05-12 18:07 UTC

**Comment by Kraxxis** [comment] 2017-05-12 18:24
@sindresorhus Thank you for the update. After installing the latest, i no longer have this issue.

@kaicataldo Not sure why it was deleted. /shrug.
