### ISSUE TITLE
imagemin install infinite version checks

### ISSUE THREAD

**Issue by blamarvt** [imagemin/imagemin#68] opened 2014-10-21 17:49 UTC
This is more of a cry for help than anything. When imagemin 2.1.0 was released our builds started failing because `npm install` would spawn hundreds of processes like this:

https://www.dropbox.com/s/kv3zaiakwshg91v/Screenshot%202014-10-21%2001.48.08.png?dl=0

Sometimes it was gifsicle, other times it was pngquant or optipng.

The only solution I found was to cap imagemin at "2.0.0". Do you know why this might be happening or how we could avoid it? Here are our devDependencies:

    "devDependencies": {
        "browserify": "^5.11.0",
        "chai": "^1.9.1",
        "event-stream": "^3.1.7",
        "gulp": "^3.8.7",
        "gulp-awspublish": "0.0.23",
        "gulp-cache": "^0.2.2",
        "gulp-cssmin": "^0.1.6",
        "gulp-imagemin": "^1.0.1",
        "gulp-kss": "^0.0.2",
        "gulp-rev": "^1.1.0",
        "gulp-s3": "^0.3.0",
        "gulp-template": "^1.0.1",
        "gulp.spritesmith": "^1.2.0",
        "gulp-sass": "^0.7.3",
        "gulp-strip-react-dom-comment": "^0.0.5",
        "gulp-template": "^1.0.1",
        "gulp-uglify": "^1.0.0",
        "gulp-yuidoc": "^0.1.2",
        "karma": "^0.12.23",
        "karma-bro": "^0.7.0",
        "karma-chai": "^0.1.0",
        "karma-chai-sinon": "^0.1.3",
        "karma-chrome-launcher": "^0.1.4",
        "karma-cli": "0.0.4",
        "karma-junit-reporter": "^0.2.2",
        "karma-mocha": "^0.1.9",
        "karma-phantomjs-launcher": "^0.1.4",
        "mocha": "^1.21.4",
        "phantomjs": "^1.9.7-15",
        "reactify": "^0.14.0",
        "sinon": "^1.10.3",
        "sinon-chai": "^2.5.0",
        "vinyl-source-stream": "^0.1.1"
    },

And as you can see we're not explicitly depending on imagemin but getting it through gulp-imagemin.

Any thoughts / help? Many thanks for taking a look and let me know if more information is needed.

**Comment by maranomynet** [comment] 2015-01-05 16:12
Our team is seeing this on OSX too.

The install creates a circular reference loop between `.bin/pngquant` which spawns `vendor/pngquant` which happens to be a symbolic link to ...you guessed it... `.bin/pngquant`. :-)

We've been using frontend-maven-plugin and it installs `node 0.10.3x` and `npm 1.4.21`.

**Comment by karlvr** [comment] 2015-01-20 19:21
We also have this problem. Also when `npm install` is run by the frontend-maven plugin. It appears that if we run `npm install` directly we have no issues. So it seems pretty likely that there's something about npm being run from the frontend-maven-plugin that is causing this issue. Perhaps a `PATH` issue, given that it's not running in a regular user shell? I'm intending to make time to investigate further because all these node processes are taking over.

**Comment by kevva** [comment] 2015-01-20 19:31
Yeah, it'd be helpful since I haven't been able to reproduce this.

**Comment by almeric** [comment] 2015-01-28 10:36
Small update:  
  
These issues cropped up on our CI server on which I made a symbolic link to a node modules directory during building to speed up the process.  
  
If don't link the node_modules directory and just `npm install` the issue is gone. So maybe it failed due to my `ln -s` shenanigans?

**Comment by karlvr** [comment] 2015-02-03 01:20
I have found the cause of this issue, and submitted a pull request to the fronted-maven-plugin project eirslett/frontend-maven-plugin#150

**Comment by karlvr** [comment] 2015-02-03 01:36
@almeric I think your issue is definitely related to kevva/bin-runner#35, perhaps more than this issue.

**Comment by caseywebdev** [comment] 2015-02-06 22:05
I'm running into this issue as well.

**Comment by kevva** [comment] 2015-02-07 14:52
I'm rewriting bin-wrapper so expect a fix soon.

**Comment by caseywebdev** [comment] 2015-02-07 16:26
:+1:

**Comment by caseywebdev** [comment] 2015-02-16 13:41
I see the `bin-wrapper` fix is out. Any news on bumping the dependency here for `imagemin`?

**Comment by synapticism** [comment] 2015-03-10 20:10
I'm also having this problem by way of `gulp-imagemin` on OS X.

**Comment by eerrecalde** [comment] 2015-03-12 11:58
Same here.. (OS X) When run npm install and there is gulp-imagemin (any version) as dependency, or even trying to install only gulp-imagemin, I gets the following:

npm WARN engineStrict Per-package engineStrict (found in package.json for vinyl-fs)
npm WARN engineStrict won't be used in npm 3+. Use the config setting `engine-strict` instead.
npm ERR! unpack Could not read data for bl@0.9.4
npm ERR! unpack Could not read data for end-of-stream@1.1.0

My workmates don't have the problem when try the same installation in the same project. 
I've also tried with different (node, npm) combinations.

**Comment by kevva** [comment] 2015-03-12 13:38
@eerrecalde, that's a completely different problem.

**Comment by vmarkovtsev** [comment] 2015-03-12 15:10
I experienced this bug, too. node_modules directory was indeed a symlink.

**Comment by vmarkovtsev** [comment] 2015-04-02 13:33
I tested this with bin-wrapper 3.0.0 and the issue is still present. It just does not work. Please do not close  after merging version bumps.

**Comment by vmarkovtsev** [comment] 2015-04-02 15:14
Ok, I am starting to understand this f*cking behavior. I inserted `console.log(bin);` in lib/install.js and here is how to reproduce the problem:

```bash
mkdir other && cd other
ln -s ../node_modules node_modules
npm install /path/to/modified/gifsicle-bin
```

it prints the following and then explodes:
```
{ env: 
   [ '/usr/lib/node_modules/npm/bin/node-gyp-bin',
     '/.../other/node_modules/gifsicle-bin/node_modules/.bin',
     '/.../other/node_modules/.bin',
     '/usr/local/sbin',
     '/usr/local/bin',
     '/usr/sbin',
     '/usr/bin',
     '/sbin',
     '/bin',
     '/usr/games',
     '/usr/local/games' ],
  opts: { global: true, progress: false, strip: 1 },
  _src: 
   [ { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/osx/gifsicle',
       os: 'darwin',
       arch: undefined },
     { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/linux/x86/gifsicle',
       os: 'linux',
       arch: 'x86' },
     { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/linux/x64/gifsicle',
       os: 'linux',
       arch: 'x64' },
     { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/freebsd/x86/gifsicle',
       os: 'freebsd',
       arch: 'x86' },
     { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/freebsd/x64/gifsicle',
       os: 'freebsd',
       arch: 'x64' },
     { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/win/x86/gifsicle.exe',
       os: 'win32',
       arch: 'x86' },
     { url: 'https://raw.github.com/imagemin/gifsicle-bin/v2.0.1/vendor/win/x64/gifsicle.exe',
       os: 'win32',
       arch: 'x64' } ],
  _dest: '/.../node_modules/gifsicle-bin/vendor',
  _use: 'gifsicle',
  v: '1.86' }
```

Ok, Ctrl-C. We need a better demo.
```bash
rm -rf node_modules/gifsicle-bin
cd ..
npm install gifsicle-bin
```

And now the tricky part.
```bash
cd node_modules/gifsicle-bin
PATH=/usr/lib/node_modules/npm/bin/node-gyp-bin:/.../other/node_modules/gifsicle/node_modules/.bin:/.../other/node_modules/.bin:$PATH node lib/install.js
```
We explode.

**Comment by vmarkovtsev** [comment] 2015-04-02 15:34
Ok, I found the bug. It is in bin-wrapper, symlink method, line 197.
```js
return file !== which.sync(name);
```
Paths are compared as strings, not as paths.

**Comment by hotmeteor** [comment] 2015-04-02 15:37
I hope this is it, because that would be awesome.

**Comment by vmarkovtsev** [comment] 2015-04-02 15:45
Ok, I fixed this issue and successfully installed it!

```js
return fs.realpathSync(file) !== fs.realpathSync(which.sync(name));
```

Pull request is pending...

**Comment by vmarkovtsev** [comment] 2015-04-02 15:50
Unfortunately, this is the fix for bin-wrapper 2.1.3. I will test 3.0.0 now...

**Comment by kevva** [comment] 2015-04-02 15:53
It doesn't exist in 3.0.0 because it's fixed there.

**Comment by vmarkovtsev** [comment] 2015-04-02 15:53
Yes, 3.0.0 works fine.

**Comment by vmarkovtsev** [comment] 2015-04-02 15:56
What's left to do is to override bin-wrapper version for all those *-bin packages.

**Comment by vmarkovtsev** [comment] 2015-04-02 15:59
@kevva, please make a new 2.x.y release with the fix so that the unupdated packages can be installed.

**Comment by shinnn** [comment] 2015-04-02 16:02
Related discussion (why we can't update bin-wrapper to v3.0.0 for now): https://github.com/imagemin/optipng-bin/commit/49fa6b116b4dfb27e4579b13ce81bdd90da5ff3e#commitcomment-10210176

Creating a good PR to fix https://github.com/sindresorhus/got/issues/7 would be a best solution.

**Comment by kevva** [comment] 2015-04-02 16:12
I might just release download with request again while I'm working on fixing proxies the easy way on got.

**Comment by vmarkovtsev** [comment] 2015-04-02 16:15
If anyone writes here how to install imagemin with bin-wrapper version forced to 3.0.0, I will be very grateful. Unable to proceed with PR because there are no branches in original bin-wrapper.

**Comment by vmarkovtsev** [comment] 2015-04-03 07:26
I ended up with the following script:

```bash
#!/bin/sh -e

patch_file=bin-wrapper.patch
url=https://github.com/vmarkovtsev/bin-wrapper/commit/ce620fc4f8835daa93e069a00ad13c69003e9456.patch

if [ ! -e $patch_file ]; then
  if which curl; then
    curl -o $patch_file $url
  elif which wget; then
    wget -O $patch_file $url
  else
    echo "Unable to download the patch for bin-wrapper from GitHub" 1>&2
    exit 1
  fi
fi
patch_file="$(readlink -e $patch_file)"

find node_modules -type d -name bin-wrapper -exec patch {}/index.js "$patch_file" \;
```

It should be run after imagemin installation from the real path (symlinked installation breaks vendor/*).

**Comment by guiambros** [comment] 2015-04-04 04:23
Same problem here. Tried applying the patch above, but didn't help. Running `npm install imagemin -g` still creates hundreds of processes, until I kill npm. Always stops on gifsicle.

Any idea how to solve this?

**Comment by vmarkovtsev** [comment] 2015-04-04 06:45
@guiambros As I wrote

>>> It should run after imagemin installation from the real path (symlinked installation breaks vendor/*).

In other words, you should install imagemin *normally* beforehand, without the symlinked node_modules. The proposed fix just makes imagemin usable from symlinked node_modules when imagemin's already been installed.

Thus, you change to a temporary directory, run ``npm install imagemin``, then execute the shell script from above, then replace node_modules/imagemin drectory of your site with the patched temporary.

**Comment by bevacqua** [comment] 2015-06-08 19:00
@kevva Is this issue anywhere near a solution?

**Comment by kevva** [comment] 2015-06-08 19:16
On which binary? I've published new versions with a fix the past days.

**Comment by shinnn** [comment] 2015-06-10 16:24
@bevacqua Could you run `npm ls imagemin gifsicle jpegtran-bin optipng-bin` in your project directory and show us the result?

**Comment by bevacqua** [comment] 2015-06-10 16:34
Hey guys, turns out the issue was mostly using a small EC2 instance and running out of memory. Using a larger instance solved it for me. Thanks!

**Comment by shinnn** [comment] 2015-06-10 16:37
OK, closing this issue now. Thanks for your patience, everyone.

**Closed by shinnn** 2015-06-10 16:37 UTC
Labels: bug
