### ISSUE TITLE
npm script to call out image quality

### ISSUE THREAD

**Issue by treeWater** [imagemin/imagemin#305] opened 2018-11-24 05:25 UTC
Is it possible to specify image quality when use imagemin in npm script ? Thanks,
I was using the following, I want to further compress the image so to reduce size. Can't find any instructions around about passing in the parameters for quality or other.  Please help.
```
"scripts": {
    "imageminall": "imagemin --plugin=mozjpeg images/* --out-dir=dist"
  },
```
Mozjpeg can be replaced with other plugin if needed. Thanks again.

**Comment by sindresorhus** [comment] 2018-12-25 18:54
Duplicate of #171

**Closed by sindresorhus** 2018-12-25 18:54 UTC
